mtg_scraper/app/models.py
from app import db, login
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash
from hashlib import md5
import requests
import re
from bs4 import BeautifulSoup

followers = db.Table(
    'followers',
    db.Column('follower_id', db.Integer, db.ForeignKey('user.id')),
    db.Column('followed_id', db.Integer, db.ForeignKey('user.id'))
)

card_ownership = db.Table(
    'card_ownership',
    db.Column('user_id', db.Integer, db.ForeignKey('user.id')),
    db.Column('card_id', db.Integer, db.ForeignKey('card.id'))
)

class Card(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String, index=True)
    setname = db.Column(db.String, index=True)
    foil = db.Column(db.Boolean, default=False)
    url = db.Column(db.String, index=True)
    img_url = db.Column(db.String)
    purchase_price = db.Column(db.Float)
    lowest_price = db.Column(db.Float)
    highest_price = db.Column(db.Float)
    current_price = db.Column(db.Float)
    time_updated = db.Column(db.DateTime)
    daily_change = db.Column(db.Float)
    weekly_change = db.Column(db.Float)

    def refresh(self):
        r = requests.get(self.url)
        soup = BeautifulSoup(r.text, "html.parser")
        # print(img_elem['src'])
        if self.foil:
            c = soup.find('div', class_='price-card-image-bg')
            self.img_url = re.findall('.*url\(\'(.*)\'\).*', c['style'])[0]
        else:
            img_elem = soup.find("img", class_="price-card-image-image")
            print(img_elem)
            self.img_url = img_elem['src']
        self.current_price = float(soup.find('div', class_='price-box paper').find('div', class_='price-box-price').string)
        db.session.commit()

    def from_dict(self, data):
        for key in ['name', 'setname', 'foil']:
            setattr(self, key, data[key])
        for key in ['purchase_price', 'current_price', 'lowest_price', 'highest_price', 'time_updated', 'daily_change', 'weekly_change']:
            setattr(self, key, data.get(key))

    def to_dict(self):
        data = {
            'name': self.name,
            'setname': self.setname,
            'foil': self.foil,
            'url': self.url
        } 
        return data

    @staticmethod
    def _encode_for_url_without_escapes(card_name):
        if card_name is None:
            raise ValueError("Shit's fucked, yo")
        _chars_to_remove = ["\'", ","]
        name_url = re.sub(" ", "+", card_name)
        name_url = re.sub("|".join(_chars_to_remove), "", name_url)
        return name_url

    def build_url(self):
        name_url = self._encode_for_url_without_escapes(self.name) + "#paper"
        set_url = self._encode_for_url_without_escapes(self.setname)
        if self.foil:
            set_url += ":Foil"
        url = "/".join(["https://www.mtggoldfish.com/price", set_url, name_url])
        r = request('get', url)
        if r.status_code == 200:
            self.url = url
            soup = BeautifulSoup(r.text, 'html.parser')
            img = soup.find("img", class_="price-card-image-image")
            if img is not None:
                self.img_url = img['src']

    def __repr__(self):
        return '<Card {}>'.format(self.name)

class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String, index=True, unique=True)
    email = db.Column(db.String(120), index=True, unique=True)
    password_hash = db.Column(db.String(128))
    followed = db.relationship(
        'User',
        secondary=followers,
        primaryjoin=(followers.c.followed_id == id),
        secondaryjoin=(followers.c.follower_id == id),
        backref=db.backref('followers', lazy='dynamic'), lazy='dynamic'
    )
    cards = db.relationship("Card", secondary=card_ownership)

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)
    
    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

    def avatar(self, size):
        digest = md5(self.email.lower().encode('utf-8')).hexdigest()
        return 'https://www.gravatar.com/avatar/{}?d=identicon&s={}'.format(digest, size)

    def follow(self, user):
        if not self.is_following(user):
            self.followed.append(user)

    def unfollow(self, user):
        if self.is_following(user):
            self.followed.remove(user)

    def is_following(self, user):
        return self.followed.filter(followers.c.followed_id == user.id).count() > 0

    def __repr__(self):
        return '<User {}>'.format(self.username)

@login.user_loader
def load_user(id):
    return User.query.get(id)

mtg_scraper/app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_bootstrap import Bootstrap
from flask_login import LoginManager
from config import Config


db = SQLAlchemy()
migrate = Migrate()
bootstrap = Bootstrap()
login = LoginManager()
login.login_view = 'auth.login'
login.login_message = 'Please log in to access this page'

def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(Config)

    db.init_app(app)
    migrate.init_app(app, db)
    bootstrap.init_app(app)
    login.init_app(app)


    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    from app.auth import bp as auth_bp
    app.register_blueprint(auth_bp)

    return app

from app import models

mtg_scraper/app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

mtg_scraper/app/main/routes.py
from flask import render_template
from app.main import bp
from app.models import User
from flask_login import login_required


@bp.route('/')
@bp.route('/index')
@login_required
def index():
    return render_template('index.html')

@bp.route('/<username>')
@login_required
def user(username):
    user = User.query.filter_by(username=username).first_or_404()
    return render_template('user.html', user=user, cards=user.cards)

# @bp.route('/<username>/cards')
# @login_required
# def cards(username):
#     user = User.query.filter_by(username=username).first_or_404()
#     return render_template('cards.html', cards=user.cards)

@bp.route('/edit_profile')
@login_required
def edit_profile():
    return 'edit profile page'


@bp.route('/follow/<username>')
@login_required
def follow(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        flash('User {} not found.'.format(username))
        return redirect(url_for('index'))
    if user == current_user:
        flash('You cannot follow yourself!')
        return redirect(url_for('user', username=username))
    current_user.follow(user)
    db.session.commit()
    flash('You are following {}!'.format(username))
    return redirect(url_for('user', username=username))


@bp.route('/unfollow/<username>')
@login_required
def unfollow(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        flash('User {} not found.'.format(username))
        return redirect(url_for('index'))
    if user == current_user:
        flash('You cannot unfollow yourself!')
        return redirect(url_for('user', username=username))
    current_user.unfollow(user)
    db.session.commit()
    flash('You are not following {}.'.format(username))
    return redirect(url_for('user', username=username))

mtg_scraper/app/templates/_card.html
<table class="table table-hover">
    <tr>
        <td width="70px">
            <a href="{{ url_for('main.user', username=user.username) }}">
                <img src="{{ card.img_url }}" />
            </a>
        </td>
        <td>
            <span id="card{{ card.id }}">{{ card.name }} | ${{ card.current_price}}</span>
        </td>
    </tr>
</table>

mtg_scraper/app/templates/base.html
{% extends 'bootstrap/base.html' %}

{% block title %}
    {% if title %}{{ title }} - MTG{% else %}{{ 'MTG Test' }}{% endif %}
{% endblock %}

{% block navbar %}
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('main.index') }}">MTG Test</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('main.index') }}">Home</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if current_user.is_anonymous %}
                    <li><a href="{{ url_for('auth.login') }}">Login</a></li>
                    {% else %}
                    <li><a href="{{ url_for('main.user', username=current_user.username) }}">Profile</a></li>
                    <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
{% endblock %}

{% block content %}
    <div class="container">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-info" role="alert">{{ message }}</div>
            {% endfor %}
        {% endif %}
        {% endwith %}

        {# application content needs to be provided in the app_content block #}
        {% block app_content %}{% endblock %}
    </div>
{% endblock %}

mtg_scraper/app/templates/index.html
{% extends "base.html" %}

{% block app_content %}
    <h1>Hi, {{current_user.username }}</h1>
    <nav aria-label="...">
        <ul class="pager">
            <li class="previous{% if not prev_url %} disabled{% endif %}">
                <a href="{{ prev_url or '#' }}">
                    <span aria-hidden="true">&larr;</span> {{ 'Newer posts' }}
                </a>
            </li>
            <li class="next{% if not next_url %} disabled{% endif %}">
                <a href="{{ next_url or '#' }}">
                    {{ 'Older posts' }} <span aria-hidden="true">&rarr;</span>
                </a>
            </li>
        </ul>
    </nav>
{% endblock %}

mtg_scraper/app/templates/user.html
{% extends "base.html" %}

{% block app_content %}
    <table class="table table-hover">
        <tr>
            <td width="256px"><img src="{{ user.avatar(256) }}"></td>
            <td>
                <h1>User: {{ user.username }}</h1>
                {% if user.about_me %}<p>{{ user.about_me }}</p>{% endif %}
                {% if user.last_seen %}
                <p>Last seen on: {{ moment(user.last_seen).format('LLL') }}</p>
                {% endif %}
                <p>{{ user.followers.count() }} followers, {{ user.followed.count() }} followed</p>
                {% if user == current_user %}
                <p><a href="{{ url_for('main.edit_profile') }}">Edit your profile</a></p>
                {% elif not current_user.is_following(user) %}
                <p><a href="{{ url_for('main.follow', username=user.username) }}">Follow</a></p>
                {% else %}
                <p><a href="{{ url_for('main.unfollow', username=user.username) }}">Unfollow</a></p>
                {% endif %}
            </td>
        </tr>
    </table>
    {% for card in cards %}
        {% include '_card.html' %}
    {% endfor %}
    <nav aria-label="...">
        <ul class="pager">
            <li class="previous{% if not prev_url %} disabled{% endif %}">
                <a href="{{ prev_url or '#' }}">
                    <span aria-hidden="true">&larr;</span>Newer cards
                </a>
            </li>
            <li class="next{% if not next_url %} disabled{% endif %}">
                <a href="{{ next_url or '#' }}">
                    Older cards<span aria-hidden="true">&rarr;</span>
                </a>
            </li>
        </ul>
    </nav>
{% endblock %}